# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: right29
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: notes-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: notes-api


package:
  individually: true

plugins:
- serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  stage: prod
  region: ap-south-1

  environment:
    TABLE_NAME: notes  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  
  create:
    handler: create.main
    events:
      - http:
          path: notes
          method: post
          authorizer: aws_iam

  get:
    handler: get.main
    events:
      - http:
          path: notes/{id}
          method: get
          authorizer: aws_iam
  list:
    handler: list.main
    events:
      - http:
          path: notes
          method: get
          authorizer: aws_iam
  update:
    handler: update.main
    events:
      - http:
          path: notes/{id}
          method: put
          authorizer: aws_iam
  delete:
    handler: delete.main
    events:
      - http:
          path: notes/{id}
          method: delete
          authorizer: aws_iam
